Repository sad-company/sad-tetrispy, pull requests merged in 2022-11, with the labels that each got.

#13 Func & test for is_on_bottom()
  src/board.py
  src/point.py
  tests/test_Board.py
Labels: enhancement

#17 ✅ BoardConverterTestCase.test_convert_to_string()
  tests/test_BoardConverter.py
Labels: tests

#19 📝 Add unittests command
  README.md
Labels: documentation

#21 ✅ FigureMoverTestCase: cover with tests
  tests/test_FigureMover.py
Labels: tests

#24 ✨ Remove lines
  src/board.py
Labels: enhancement

#26 ✅ Update FigureMoverTestCase
  tests/test_FigureMover.py
Labels: tests

#28 ✨ support EngineEvent.PAUSE
  src/engine.py
  src/engine_event_handler.py
Labels: enhancement
